Login Errors
devpointlabs/query pull request #48
Opened 2019-04-04 04:34 UTC by baardvark

2019-04-04 16:51 UTC, spenhappenin approved these changes

2019-04-04 19:39 UTC, jessieleigh30 approved these changes

2019-04-04 23:19 UTC, jessieleigh30 requested changes
you just need to delete your package-lock.json file and then push again. Then let the team know they will need to yarn again after they pull.

2019-04-05 18:23 UTC, baardvark commented
Deleted the package-lock.json file and added the Student Dashboard

2019-04-05 19:45 UTC, jessieleigh30 approved these changes

2019-04-05 20:16 UTC, merged